global_options:
  dart_mappable_builder:
    options:
      caseStyle: camelCase
      enumCaseStyle: camelCase
      ignoreNull: false
      discriminatorKey: type
#      # used to specify which methods to generate (all by default)
#      generateMethods: [decode, encode, copy, stringify, equals]