global_options:
  dart_mappable_builder:
    options:
      caseStyle: none
      enumCaseStyle: none
      ignoreNull: false
      discriminatorKey: __type
targets:
  $default:
    builders:
      dart_mappable_builder:
        options:
          build_extensions:
            'lib/{{path}}/{{file}}.dart':
              - 'lib/{{path}}/{{file}}.mapper.dart'
              - 'lib/{{path}}/{{file}}.init.dart'