// coverage:ignore-file
// GENERATED CODE - DO NOT MODIFY BY HAND
// dart format off
// ignore_for_file: type=lint
// ignore_for_file: unused_element

import '../app/services/game_settings_service.dart' as p0;
import '../app/services/keybinding_service.dart' as p1;
import 'ai/behaviors/behaviors.dart' as p2;
import 'ai/composite_nodes.dart' as p3;
import 'ai/decorator_nodes.dart' as p4;
import 'ai/leaf_nodes.dart' as p5;
import 'ai/nodes.dart' as p6;
import 'components.dart' as p7;
import 'dialog/dialog_conditions.dart' as p8;
import 'dialog/dialog_content_nodes.dart' as p9;
import 'dialog/dialog_effects.dart' as p10;
import 'dialog/dialog_nodes.dart' as p11;
import 'entity_template.dart' as p12;
import 'systems/behavior_system.dart' as p13;
import 'systems/collision_system.dart' as p14;
import 'systems/combat_system.dart' as p15;
import 'systems/control_system.dart' as p16;
import 'systems/death_system.dart' as p17;
import 'systems/direction_system.dart' as p18;
import 'systems/inventory_system.dart' as p19;
import 'systems/movement_system.dart' as p20;
import 'systems/openable_system.dart' as p21;
import 'systems/portal_system.dart' as p22;
import 'systems/save_system.dart' as p23;
import 'systems/system.dart' as p24;
import 'systems/vision_system.dart' as p25;
import 'world.dart' as p26;

void initializeMappers() {
  p0.GameSettingsMapper.ensureInitialized();
  p0.InteractionMacroModeMapper.ensureInitialized();
  p1.KeyComboMapper.ensureInitialized();
  p1.KeyBindingMapper.ensureInitialized();
  p2.MoveRandomlyNodeMapper.ensureInitialized();
  p3.SelectorMapper.ensureInitialized();
  p3.ParallelMapper.ensureInitialized();
  p3.RandomSelectorMapper.ensureInitialized();
  p4.InverterMapper.ensureInitialized();
  p4.RepeaterMapper.ensureInitialized();
  p4.GuardMapper.ensureInitialized();
  p4.TimeoutMapper.ensureInitialized();
  p5.ConditionNodeMapper.ensureInitialized();
  p5.ActionNodeMapper.ensureInitialized();
  p6.NodeMapper.ensureInitialized();
  p7.ComponentMapper.ensureInitialized();
  p7.DirectionMapper.ensureInitialized();
  p7.LifetimeMapper.ensureInitialized();
  p7.BeforeTickMapper.ensureInitialized();
  p7.AfterTickMapper.ensureInitialized();
  p7.IntentComponentMapper.ensureInitialized();
  p7.WaitIntentMapper.ensureInitialized();
  p7.CellMapper.ensureInitialized();
  p7.NameMapper.ensureInitialized();
  p7.LocalPositionMapper.ensureInitialized();
  p7.MoveByIntentMapper.ensureInitialized();
  p7.DidMoveMapper.ensureInitialized();
  p7.DirectionIntentMapper.ensureInitialized();
  p7.DidChangeDirectionMapper.ensureInitialized();
  p7.BlocksMovementMapper.ensureInitialized();
  p7.BlockedMoveMapper.ensureInitialized();
  p7.AiControlledMapper.ensureInitialized();
  p7.PlayerMapper.ensureInitialized();
  p7.BehaviorMapper.ensureInitialized();
  p7.RenderableAssetMapper.ensureInitialized();
  p7.ImageAssetMapper.ensureInitialized();
  p7.TextAssetMapper.ensureInitialized();
  p7.RenderableMapper.ensureInitialized();
  p7.EditorRenderableMapper.ensureInitialized();
  p7.DirectionBasedRenderingMapper.ensureInitialized();
  p7.HealthMapper.ensureInitialized();
  p7.AttackIntentMapper.ensureInitialized();
  p7.DidAttackMapper.ensureInitialized();
  p7.WasAttackedMapper.ensureInitialized();
  p7.DeadMapper.ensureInitialized();
  p7.InventoryMapper.ensureInitialized();
  p7.InventoryMaxCountMapper.ensureInitialized();
  p7.InventoryFullFailureMapper.ensureInitialized();
  p7.PickupableMapper.ensureInitialized();
  p7.PickupIntentMapper.ensureInitialized();
  p7.PickedUpMapper.ensureInitialized();
  p7.BlocksSightMapper.ensureInitialized();
  p7.VisionRadiusMapper.ensureInitialized();
  p7.VisibleEntitiesMapper.ensureInitialized();
  p7.VisionMemoryMapper.ensureInitialized();
  p7.HasParentMapper.ensureInitialized();
  p7.PortalToPositionMapper.ensureInitialized();
  p7.PortalToAnchorMapper.ensureInitialized();
  p7.PortalAnchorMapper.ensureInitialized();
  p7.UsePortalIntentMapper.ensureInitialized();
  p7.DidPortalMapper.ensureInitialized();
  p7.FailedToPortalMapper.ensureInitialized();
  p7.ControllableMapper.ensureInitialized();
  p7.ControllingMapper.ensureInitialized();
  p7.EnablesControlMapper.ensureInitialized();
  p7.DockedMapper.ensureInitialized();
  p7.WantsControlIntentMapper.ensureInitialized();
  p7.ReleasesControlIntentMapper.ensureInitialized();
  p7.DockIntentMapper.ensureInitialized();
  p7.UndockIntentMapper.ensureInitialized();
  p7.OpenableMapper.ensureInitialized();
  p7.OpenIntentMapper.ensureInitialized();
  p7.CloseIntentMapper.ensureInitialized();
  p7.DidOpenMapper.ensureInitialized();
  p7.DidCloseMapper.ensureInitialized();
  p7.DialogMapper.ensureInitialized();
  p7.TalkIntentMapper.ensureInitialized();
  p7.IsTemplateMapper.ensureInitialized();
  p7.FromTemplateMapper.ensureInitialized();
  p7.ItemMapper.ensureInitialized();
  p7.DescriptionMapper.ensureInitialized();
  p7.LootEntryMapper.ensureInitialized();
  p7.LootTableMapper.ensureInitialized();
  p7.CompassDirectionMapper.ensureInitialized();
  p7.PortalFailureReasonMapper.ensureInitialized();
  p8.DialogConditionMapper.ensureInitialized();
  p8.AlwaysConditionMapper.ensureInitialized();
  p8.NeverConditionMapper.ensureInitialized();
  p8.NotConditionMapper.ensureInitialized();
  p8.AllConditionMapper.ensureInitialized();
  p8.AnyConditionMapper.ensureInitialized();
  p8.HasItemConditionMapper.ensureInitialized();
  p8.HealthConditionMapper.ensureInitialized();
  p8.HasComponentConditionMapper.ensureInitialized();
  p8.CustomConditionMapper.ensureInitialized();
  p9.ChoiceMapper.ensureInitialized();
  p9.SpeakNodeMapper.ensureInitialized();
  p9.TextNodeMapper.ensureInitialized();
  p9.EndNodeMapper.ensureInitialized();
  p9.EffectNodeMapper.ensureInitialized();
  p9.ConditionalNodeMapper.ensureInitialized();
  p9.GotoNodeMapper.ensureInitialized();
  p10.DialogEffectMapper.ensureInitialized();
  p10.TriggerTickEffectMapper.ensureInitialized();
  p10.HealEffectMapper.ensureInitialized();
  p10.DamageEffectMapper.ensureInitialized();
  p10.GiveItemEffectMapper.ensureInitialized();
  p10.RemoveItemEffectMapper.ensureInitialized();
  p10.TeleportEffectMapper.ensureInitialized();
  p10.MoveEntityEffectMapper.ensureInitialized();
  p10.OpenDoorEffectMapper.ensureInitialized();
  p10.CloseDoorEffectMapper.ensureInitialized();
  p10.SetParentEffectMapper.ensureInitialized();
  p10.RemoveParentEffectMapper.ensureInitialized();
  p10.AddComponentEffectMapper.ensureInitialized();
  p10.RemoveComponentEffectMapper.ensureInitialized();
  p10.SequenceEffectMapper.ensureInitialized();
  p10.CustomEffectMapper.ensureInitialized();
  p11.DialogResultMapper.ensureInitialized();
  p11.DialogAwaitingChoiceMapper.ensureInitialized();
  p11.DialogEndedMapper.ensureInitialized();
  p11.DialogChoiceMapper.ensureInitialized();
  p11.DialogNodeMapper.ensureInitialized();
  p12.EntityTemplateMapper.ensureInitialized();
  p13.BehaviorSystemMapper.ensureInitialized();
  p14.CollisionSystemMapper.ensureInitialized();
  p15.CombatSystemMapper.ensureInitialized();
  p16.ControlSystemMapper.ensureInitialized();
  p17.DeathSystemMapper.ensureInitialized();
  p18.DirectionSystemMapper.ensureInitialized();
  p19.InventorySystemMapper.ensureInitialized();
  p20.MovementSystemMapper.ensureInitialized();
  p21.OpenableSystemMapper.ensureInitialized();
  p22.PortalSystemMapper.ensureInitialized();
  p23.SaveSystemMapper.ensureInitialized();
  p24.SystemMapper.ensureInitialized();
  p24.BudgetedSystemMapper.ensureInitialized();
  p25.VisionSystemMapper.ensureInitialized();
  p26.WorldMapper.ensureInitialized();
}

